// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReliefNexus.API.Data;

#nullable disable

namespace ReliefNexus.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817134849_AddDisasterRiskAssessment")]
    partial class AddDisasterRiskAssessment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReliefNexus.API.Models.RiskAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisasterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("RiskAssessments");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskAssessmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RiskAssessmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RiskAssessmentId");

                    b.ToTable("RiskAssessmentHistories");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FactorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FactorValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RiskAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RiskAssessmentId");

                    b.ToTable("RiskFactors");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PredictedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PredictionSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RiskAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RiskAssessmentId")
                        .IsUnique();

                    b.ToTable("RiskPredictions");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskAssessment", b =>
                {
                    b.HasOne("ReliefNexus.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskAssessmentHistory", b =>
                {
                    b.HasOne("ReliefNexus.API.Models.RiskAssessment", "RiskAssessment")
                        .WithMany("History")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskFactor", b =>
                {
                    b.HasOne("ReliefNexus.API.Models.RiskAssessment", "RiskAssessment")
                        .WithMany("RiskFactors")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskPrediction", b =>
                {
                    b.HasOne("ReliefNexus.API.Models.RiskAssessment", "RiskAssessment")
                        .WithOne("RiskPrediction")
                        .HasForeignKey("ReliefNexus.API.Models.RiskPrediction", "RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskAssessment", b =>
                {
                    b.Navigation("History");

                    b.Navigation("RiskFactors");

                    b.Navigation("RiskPrediction");
                });
#pragma warning restore 612, 618
        }
    }
}
