// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReliefNexus.API.Data;

#nullable disable

namespace ReliefNexus.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002142942_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReliefNexus.API.Models.CriticalInfrastructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmergencyHub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("OperationalCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffectedAreaId")
                        .HasDatabaseName("ix_critical_infrastructures_affected_area_id");

                    b.HasIndex("AffectedAreaId", "Type")
                        .HasDatabaseName("ix_critical_infrastructures_area_type");

                    b.ToTable("critical_infrastructures", (string)null);
                });

            modelBuilder.Entity("ReliefNexus.API.Models.ImpactAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedFacilitiesSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DisasterEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedPeopleAtRisk")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedVulnerableGroups")
                        .HasColumnType("integer");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("VulnerabilityAgent");

                    b.Property<string>("ImpactSeverity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("LOW");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AffectedAreaId")
                        .HasDatabaseName("ix_impact_assessments_affected_area_id");

                    b.HasIndex("DisasterEventId")
                        .HasDatabaseName("ix_impact_assessments_disaster_event_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_impact_assessments_workflow_id");

                    b.ToTable("impact_assessments", (string)null);
                });

            modelBuilder.Entity("ReliefNexus.API.Models.PopulationRiskSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisabledCount")
                        .HasColumnType("integer");

                    b.Property<int>("ElderlyCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPopulation")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffectedAreaId")
                        .HasDatabaseName("ix_population_risk_snapshots_affected_area_id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("ix_population_risk_snapshots_snapshot_date");

                    b.ToTable("population_risk_snapshots", (string)null);
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskAgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RiskPredictionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RiskAgentExecutions");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Contribution")
                        .HasColumnType("double precision");

                    b.Property<string>("Factor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RiskPredictionId")
                        .HasColumnType("uuid");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RiskPredictionId");

                    b.ToTable("RiskFactors", (string)null);
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisasterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DrainageCapacity")
                        .HasColumnType("double precision");

                    b.Property<double>("Elevation")
                        .HasColumnType("double precision");

                    b.Property<double>("ForecastRainfall")
                        .HasColumnType("double precision");

                    b.Property<int>("HistoricalFloodCount")
                        .HasColumnType("integer");

                    b.Property<double>("HistoricalSeverity")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PopulationDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("PredictionSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rainfall1h")
                        .HasColumnType("double precision");

                    b.Property<double>("Rainfall24h")
                        .HasColumnType("double precision");

                    b.Property<double>("Rainfall3h")
                        .HasColumnType("double precision");

                    b.Property<bool>("RequiresHumanApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<double>("RiverFlow")
                        .HasColumnType("double precision");

                    b.Property<double>("RiverLevel")
                        .HasColumnType("double precision");

                    b.Property<double>("SoilMoisture")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("RiskPredictions", (string)null);
                });

            modelBuilder.Entity("ReliefNexus.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleRequestStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskFactor", b =>
                {
                    b.HasOne("ReliefNexus.API.Models.RiskPrediction", "RiskPrediction")
                        .WithMany("RiskFactors")
                        .HasForeignKey("RiskPredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskPrediction");
                });

            modelBuilder.Entity("ReliefNexus.API.Models.RiskPrediction", b =>
                {
                    b.Navigation("RiskFactors");
                });
#pragma warning restore 612, 618
        }
    }
}
