using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReliefNexus.API.Models;

/// <summary>
/// Component 2 – Population Vulnerability &amp; Impact Assessment.
/// Represents a physical critical infrastructure facility (hospital, school, power station, etc.)
/// located within an affected geographic area.
/// Coordinates are stored as decimal degrees (WGS-84) for GIS compatibility.
/// </summary>
public class CriticalInfrastructure
{
    /// <summary>Primary key – GUID generated by the application layer.</summary>
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    // ─────────────────────────────────────────────────────────────────────────
    // Foreign Keys  (shared entities owned by Component 1 / core schema)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// FK → AffectedAreas table (managed by Component 1 / core schema).
    /// Links this facility to its geographic disaster zone.
    /// </summary>
    [Required]
    public Guid AffectedAreaId { get; set; }

    // ─────────────────────────────────────────────────────────────────────────
    // Facility Identity
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>Human-readable name of the facility (e.g., "Civil Hospital Karachi").</summary>
    [Required]
    [MaxLength(150)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Categorisation of the facility type.
    /// Allowed values: "Hospital", "School", "PowerStation", "WaterPlant",
    /// "Shelter", "FireStation", "PoliceStation", "Bridge", "Other".
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string Type { get; set; } = string.Empty;

    // ─────────────────────────────────────────────────────────────────────────
    // Geospatial Coordinates  (WGS-84 decimal degrees)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>Latitude in decimal degrees (WGS-84). Range: –90 to +90.</summary>
    [Range(-90.0, 90.0, ErrorMessage = "Latitude must be between -90 and 90.")]
    public double Latitude { get; set; }

    /// <summary>Longitude in decimal degrees (WGS-84). Range: –180 to +180.</summary>
    [Range(-180.0, 180.0, ErrorMessage = "Longitude must be between -180 and 180.")]
    public double Longitude { get; set; }

    // ─────────────────────────────────────────────────────────────────────────
    // Operational Attributes
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Normal operational capacity (e.g., bed count for hospitals,
    /// student/seat count for schools). Null if not applicable.
    /// </summary>
    [Range(0, int.MaxValue)]
    public int? OperationalCapacity { get; set; }

    /// <summary>
    /// Indicates whether this facility is designated as an emergency hub
    /// during a disaster response. Defaults to false.
    /// </summary>
    public bool IsEmergencyHub { get; set; } = false;

    // ─────────────────────────────────────────────────────────────────────────
    // Audit Fields
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>UTC timestamp when this record was first persisted.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the last update, null if never updated.</summary>
    public DateTime? UpdatedAt { get; set; }
}
