using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReliefNexus.API.Models;

/// <summary>
/// Component 2 – Population Vulnerability &amp; Impact Assessment.
/// Represents a computed or agent-generated impact assessment record
/// linking a specific disaster event to an affected area, capturing
/// exposure estimates and severity classification.
///
/// Human-in-the-loop note:
///   Assessments generated by the VulnerabilityAgent (AI) are persisted
///   in a "pending" state and MUST receive human approval via the React
///   dashboard before any automated downstream action is triggered.
///   This is enforced at the service layer, not the model layer.
/// </summary>
public class ImpactAssessment
{
    /// <summary>Primary key – GUID generated by the application layer.</summary>
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    // ─────────────────────────────────────────────────────────────────────────
    // Foreign Keys  (shared entities owned by Component 1 / core schema)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// FK → DisasterEvents table (managed by Component 1 / core schema).
    /// Associates this assessment with the triggering disaster event.
    /// </summary>
    [Required]
    public Guid DisasterEventId { get; set; }

    /// <summary>
    /// FK → AffectedAreas table (managed by Component 1 / core schema).
    /// Identifies the geographic boundary evaluated in this assessment.
    /// </summary>
    [Required]
    public Guid AffectedAreaId { get; set; }

    // ─────────────────────────────────────────────────────────────────────────
    // Impact Estimates  (aggregated, no PII)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Estimated total number of people at risk within the affected area.
    /// Derived from PopulationRiskSnapshot data and hazard zone overlap.
    /// </summary>
    [Required]
    [Range(0, int.MaxValue, ErrorMessage = "EstimatedPeopleAtRisk must be a non-negative integer.")]
    public int EstimatedPeopleAtRisk { get; set; }

    /// <summary>
    /// Estimated count of vulnerable individuals (children + elderly + disabled)
    /// at risk within the affected area.
    /// </summary>
    [Range(0, int.MaxValue)]
    public int EstimatedVulnerableGroups { get; set; }

    // ─────────────────────────────────────────────────────────────────────────
    // Severity Classification
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Computed impact severity level.
    /// Allowed values: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL".
    /// Calculated by the domain business rule in ImpactAssessmentService.
    /// </summary>
    [Required]
    [MaxLength(20)]
    public string ImpactSeverity { get; set; } = "LOW";

    // ─────────────────────────────────────────────────────────────────────────
    // Facility Impact Summary
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// JSON-serialised summary of impacted CriticalInfrastructure records.
    /// Stored as a plain text/JSON string to avoid tight coupling with
    /// infrastructure schema evolution.
    /// Example: [{"id":"...","name":"Civil Hospital","type":"Hospital"}]
    /// </summary>
    [Column(TypeName = "text")]
    public string? AffectedFacilitiesSummary { get; set; }

    // ─────────────────────────────────────────────────────────────────────────
    // Agentic AI Workflow Linkage
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Optional reference to the VulnerabilityAgent workflow execution ID.
    /// Null for manually created assessments.
    /// Used to correlate this record with the Python LangGraph workflow state.
    /// </summary>
    public Guid? WorkflowId { get; set; }

    /// <summary>
    /// Indicates which actor generated this assessment.
    /// Defaults to "VulnerabilityAgent" for AI-generated records;
    /// override to "Manual" for human-created records.
    /// </summary>
    [MaxLength(50)]
    public string GeneratedBy { get; set; } = "VulnerabilityAgent";

    // ─────────────────────────────────────────────────────────────────────────
    // Audit Fields
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>UTC timestamp when this record was first persisted.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the last update, null if never updated.</summary>
    public DateTime? UpdatedAt { get; set; }
}
