using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReliefNexus.API.Models;

/// <summary>
/// Component 2 – Population Vulnerability &amp; Impact Assessment.
/// Stores an aggregated, privacy-safe snapshot of population demographics
/// for a given affected area at a specific point in time.
/// NOTE: No PII (names, NIC numbers, private addresses) is stored here.
/// </summary>
public class PopulationRiskSnapshot
{
    /// <summary>Primary key – GUID generated by the application layer.</summary>
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    // ─────────────────────────────────────────────────────────────────────────
    // Foreign Keys  (shared entities owned by Component 1 / core schema)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// FK → AffectedAreas table (managed by Component 1 / core schema).
    /// Identifies the geographic boundary this snapshot covers.
    /// </summary>
    [Required]
    public Guid AffectedAreaId { get; set; }

    // ─────────────────────────────────────────────────────────────────────────
    // Aggregated Demographic Counts  (NEVER store individual-level PII)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>Total aggregated population count within the affected area.</summary>
    [Required]
    [Range(0, int.MaxValue, ErrorMessage = "TotalPopulation must be a non-negative integer.")]
    public int TotalPopulation { get; set; }

    /// <summary>Aggregated count of children (typically age 0–14).</summary>
    [Range(0, int.MaxValue)]
    public int ChildrenCount { get; set; }

    /// <summary>Aggregated count of elderly individuals (typically age 65+).</summary>
    [Range(0, int.MaxValue)]
    public int ElderlyCount { get; set; }

    /// <summary>Aggregated count of individuals with registered disabilities.</summary>
    [Range(0, int.MaxValue)]
    public int DisabledCount { get; set; }

    // ─────────────────────────────────────────────────────────────────────────
    // Snapshot Metadata
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>UTC timestamp representing when the demographic data was recorded.</summary>
    [Required]
    public DateTime SnapshotDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Origin of the demographic data (e.g., "Census 2023", "Local Authority Report").
    /// Kept for data lineage / audit purposes only.
    /// </summary>
    [MaxLength(100)]
    public string? DataSource { get; set; }

    // ─────────────────────────────────────────────────────────────────────────
    // Audit Fields
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>UTC timestamp when this record was first persisted.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the last update, null if never updated.</summary>
    public DateTime? UpdatedAt { get; set; }
}
